---
# tasks file for lighthouse-role
- name: Install epel-release
  become: true
  ansible.builtin.yum:
    name: epel-release
    state: present
- name: Install nginx
  become: true
  ansible.builtin.yum:
    name: nginx
    state: present
  notify: Start nginx
- name: Create nginx config file
  become: true
  ansible.builtin.template:
    src: "./templates/nginx.conf.j2"
    dest: "/etc/nginx/nginx.conf"
    owner: root
    group: root
    mode: 0644
  notify: Reload nginx
- name: Install lighthouse dependencies
  become: true
  ansible.builtin.yum:
    name: git
    state: present
- name: Copy lighthouse from git
  become: true
  ansible.builtin.git:
    repo: "{{ lighthouse_git }}"
    version: master
    dest: "{{ lighthouse_dir }}"
- name: Create lighthouse config file
  become: true
  ansible.builtin.template:
    src: "./templates/lighthouse.conf.j2"
    dest: "/etc/nginx/conf.d/default.conf"
    owner: root
    group: root
    mode: 0644
- name: Change file SELinux security context
  become: true
  ansible.builtin.command: "chcon -R -t httpd_sys_content_t /home/lesnykh/lighthouse"
  notify: Reload nginx  